### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by nonlinear** [NYCPrepared/v2#8]
(logo, badges, promotional objects, etc)

**Comment by nonlinear** [comment]
@devinbalkind I guess I came with a cool branding... It's solid but also versatile.
[brand studies.pdf](https://github.com/NYCPrepared/v2/files/110466/brand.studies.pdf)

**Comment by nonlinear** [comment]
Also, I'm using bit torrent for design elements. It's like dropbox but no caps.

https://link.getsync.com/#f=NYC%20Prepared&sz=34E6&t=1&s=W35MX4ZV7RL3MIY7GW4SUQCB5776SP5I&i=CGPWIFE4R4VTD53AWIAIFKXRROG6KV7RJ&v=2.2

**Comment by devinbalkind** [comment]
Haha yes it appears you did make cool branding.

What do you think of "Sharing is Caring" as a phrase to play with?

Also - my Ubuntu isn't getting along with the BitTorrent client. Wanna use Google Drive for now? I have nonprofit accounts so basically unlimited data there. Or Spider Oak. or Sandstorm.io?

**Comment by devinbalkind** [comment]
And I think we could drop "disaster relief" from the description.

"A network of volunteers and professionals sharing information and assistance." 

Vague is cool - a bit mysterious. :)

**Comment by nonlinear** [comment]
I like you want the casting thing. Well discuss.

Ill discussed about map polygons and decision maps with a developer friend
of mine, hell help.

In the end tools are there... All we need is a proper data model, choose
right tools and get the message pitch perfect.

**Comment by nonlinear** [comment]
Disaster relief is one of the possibilities, not the main one. It sounds
terrible, but the idea is a flash mob of help.

**Comment by devinbalkind** [comment]
Sometimes a flash mob, sometimes a wave.
